print("hello karthik")
print("2k26 is all yours make this day count")
print("anaconda")
print("at the end of the day you are all alone but not lonely , remember karthik you always have you ")
print("this day needed to be remembered its nothing so dont invest time on that")
print("everything happening right now is like a mess but i need to adpat to it no matter what with right efforts and practice the journey is like cake walk for me")
